version: "1.0"
services:
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      - MONGODB_URI=mongodb://database:27017/golestan
  database:
    image: mongo
    container_name: database
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis
    container_name: redis
    restart: always